name: C/C++ Build Library and Run Tests

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

  #push:
    #branches: [ "master" ]
  #pull_request:
    #branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: make
      run: make
